### ISSUE TITLE
Update rex logic

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/obe-indexer#7]
Initial scan is done correctly but we should be switching to polling logic after the initial load.

Polling can be done against the buyrex/sellrex actions to collect a list of accounts, then for each account update their rex numbers.

Right now it does a full table scan on some interval which will use a lot of resources and people have to wait for that full table scan before their rex balance would reflect.

**Comment by karynemayer** [comment]
Duplicate of https://github.com/telosnetwork/obe-indexer/issues/22
